baseURL = 'https://brunobr.uno/'
languageCode = 'pt-br'
title = 'Bruno Silva'
theme = 'ykkfromzero'


[params]
  favicon="favicon.ico"
  math = true


# Enabling math
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]